### ISSUE TITLE
Composer could not find the 'jwage/changelog-generator' package

### ISSUE THREAD

**Issue by prisis** [jwage/changelog-generator#33]
https://packagist.org/?query=jwage%2Fchangelog-generator

**Comment by Majkl578** [comment]
Hmm, this should probably be `project`, not `library` (in composer.json).

**Comment by prisis** [comment]
Library its okay, https://getcomposer.org/doc/04-schema.md#type
the question is if the package was submitted to packagist

**Comment by jwage** [comment]
You are right, I forgot to submit this package to packagist :) It is there now. Thanks!
