### ISSUE TITLE
Option to add user, password or token to the request

### ISSUE THREAD

**Issue by prisis** [jwage/changelog-generator#40]
To fix the [Github api limit](https://developer.github.com/v3/rate_limit/)

**Comment by OskarStark** [comment]
Token would be best imo

**Comment by prisis** [comment]
I would like to add both options :)

**Comment by rdohms** [comment]
Not only to solve the API issue, but also so we can use this for private packages, in my company we maintain many internal packages and we still use changelogs as a means of communication. 

The previous package also used the token solution and was pretty good.
