### ISSUE TITLE
422 - Validation Failed

### ISSUE THREAD

**Issue by rdohms** [jwage/changelog-generator#55]
After adding OAuth Token and credentials, I now see a 422 error being returned.

> In IssueClient.php line 57:
> API call to GitHub failed with status code 422 and message "Validation Failed"

Trying to figure out more info, but already opening this issue in case it rings a bell to anyone.

**Comment by rdohms** [comment]
Totally bogus, my bad.

**Comment by jwage** [comment]
What was the issue? Did the token not have the correct perms?

**Comment by rdohms** [comment]
I forgot to load up the config :D
