### ISSUE TITLE
`php:~8.0.0` support

### ISSUE THREAD

**Issue by Ocramius** [jwage/changelog-generator#64]
Not much to be said here, other than needing to widen ranges and try out stuff again before releasing :-)

**Comment by WyriHaximus** [comment]
@Ocramius Feel free to open the PR adding PHP 8 to the range 👍

**Comment by Ocramius** [comment]
Done in #65

**Comment by WyriHaximus** [comment]
Thanks :+1: !

**Comment by WyriHaximus** [comment]
Just release [`1.3.0`](https://github.com/jwage/changelog-generator/releases/tag/1.3.0)
